// Mock studies for development. Replace with Supabase queries when connected.
export const mockStudies = [
  {
    id: '1',
    title: 'Pre-Mining Baseline Water Quality: Birch Lake to BWCAW Corridor',
    author: 'Amy Ballew',
    location: 'Superior National Forest, MN',
    lat: 47.82,
    lng: -91.75,
    date_start: '2026-06-13',
    date_end: '2026-06-16',
    waterbody: 'Lake / River',
    category: 'water-quality',
    parameters: ['Dissolved Metals', 'Sulfate', 'Conductivity', 'pH', 'Dissolved Oxygen'],
    summary: 'Baseline water chemistry along the drainage corridor from Birch Lake through White Iron, Farm, and Fall Lakes into the BWCAW. Sulfate at the Dunka River inflow (14.7 mg/L) exceeds Minnesota\'s 10 mg/L wild rice standard before any mining activity. Nickel at Bob Bay is approximately 8x downstream background.',
    findings: [
      'Dunka River sulfate: 14.7 mg/L (exceeds 10 mg/L wild rice standard)',
      'Bob Bay sulfate: 10.7 mg/L (at regulatory threshold)',
      'Bob Bay nickel: 0.008 mg/L (8x background)',
      'Conductivity gradient: 144 to 35 µS/cm along corridor',
      'Arsenic and lead below detection at all sites',
    ],
    lab: 'University of Minnesota Research Analytical Lab',
    methods: 'ICP-OES 27-element dissolved metals, Ion Chromatography for anions, Apera SX751 field measurements',
    sites: 10,
    created_at: '2026-07-15',
  },
  {
    id: '2',
    title: 'Lake Vermilion Tributary Nutrient Survey',
    author: 'Northern Lakes Watershed Alliance',
    location: 'Lake Vermilion, Tower, MN',
    lat: 47.85,
    lng: -92.28,
    date_start: '2026-05-20',
    date_end: '2026-05-22',
    waterbody: 'Lake',
    category: 'water-quality',
    parameters: ['Total Phosphorus', 'Chlorophyll-a', 'Secchi Depth', 'Dissolved Oxygen'],
    summary: 'Nutrient survey of four major tributaries feeding Lake Vermilion, establishing baseline phosphorus loading before proposed shoreline development. Phosphorus ranged from 12 to 38 µg/L across sites.',
    findings: [
      'East Two River TP: 38 µg/L (elevated)',
      'Pike River TP: 12 µg/L (reference condition)',
      'Secchi depth: 2.8 to 4.5 m',
      'Chlorophyll-a correlated with TP (r² = 0.87)',
    ],
    lab: 'RMB Environmental Laboratories',
    methods: 'EPA 365.1 (TP), fluorometric chlorophyll, Secchi disk, YSI ProDSS',
    sites: 8,
    created_at: '2026-06-10',
  },
  {
    id: '3',
    title: 'St. Louis River Estuary Macroinvertebrate Assessment',
    author: 'Duluth Naturalists Collective',
    location: 'St. Louis River Estuary, Duluth, MN',
    lat: 46.72,
    lng: -92.12,
    date_start: '2026-06-01',
    date_end: '2026-06-03',
    waterbody: 'River / Estuary',
    category: 'habitat',
    parameters: ['Macroinvertebrate Index', 'Substrate Composition', 'Flow Velocity', 'Temperature'],
    summary: 'Community-led macroinvertebrate sampling at 6 sites in the restored St. Louis River estuary. EPT richness ranged from 4 to 11 taxa, with highest diversity at recently restored sites near Kingsbury Bay.',
    findings: [
      'Kingsbury Bay EPT richness: 11 taxa (highest observed)',
      'Stryker Bay EPT richness: 4 taxa (legacy contamination)',
      'Overall IBI scores suggest fair to good condition',
      'Restored sites trending toward reference conditions',
    ],
    lab: 'Field identification with MPCA protocols',
    methods: 'Hester-Dendy samplers, D-frame kick nets, MPCA macroinvertebrate IBI',
    sites: 6,
    created_at: '2026-07-01',
  },
  {
    id: '4',
    title: 'Rice Creek Stormwater Impact Monitoring',
    author: 'Rice Creek Watershed District Volunteers',
    location: 'Rice Creek, Fridley, MN',
    lat: 45.08,
    lng: -93.26,
    date_start: '2026-04-15',
    date_end: '2026-07-15',
    waterbody: 'Stream',
    category: 'water-quality',
    parameters: ['E. coli', 'Total Suspended Solids', 'Chloride', 'Conductivity'],
    summary: 'Seasonal monitoring of stormwater impacts on Rice Creek at four sites above and below urban outfalls. E. coli exceeded recreation standards at 3 of 4 sites after rain events greater than 0.5 inches.',
    findings: [
      'Post-storm E. coli: 240 to 1,800 CFU/100mL',
      'Dry-weather E. coli: 40 to 120 CFU/100mL',
      'Chloride elevated year-round (180 to 320 mg/L)',
      'TSS spikes correlate with precipitation events',
    ],
    lab: 'Minnesota Department of Health',
    methods: 'Colilert for E. coli, gravimetric TSS, IC for chloride, YSI field meter',
    sites: 4,
    created_at: '2026-07-20',
  },
  {
    id: '5',
    title: 'Manoomin (Wild Rice) Habitat Survey: Sandy Lake',
    author: 'Mille Lacs Band DNR',
    location: 'Sandy Lake, Aitkin County, MN',
    lat: 46.79,
    lng: -93.31,
    date_start: '2026-07-01',
    date_end: '2026-07-03',
    waterbody: 'Lake',
    category: 'habitat',
    parameters: ['Sulfate', 'Water Depth', 'Sediment Type', 'Wild Rice Density', 'pH'],
    summary: 'Assessment of manoomin habitat conditions at Sandy Lake, a historically significant wild rice water. Sulfate levels remain below the 10 mg/L standard at all sites (2.1 to 4.8 mg/L). Wild rice density is recovering after 2024 high water.',
    findings: [
      'Sulfate: 2.1 to 4.8 mg/L (all below 10 mg/L standard)',
      'Wild rice stem density: 8 to 22 stems/m²',
      'Sediment: organic muck, suitable for wild rice',
      'Recovery from 2024 high water event observed',
    ],
    lab: 'Field measurements and 1854 Treaty Authority Lab',
    methods: 'Quadrat sampling for rice density, YSI meter, sediment cores, IC sulfate',
    sites: 12,
    created_at: '2026-07-25',
  },
];

export function getStudyById(id) {
  return mockStudies.find(s => s.id === id) || null;
}
